In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Q1

In [7]:
pd.__version__

'3.0.5'

In [8]:
!wget https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv

--2026-09-17 10:50:24--  https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv

Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 635180 (620K) [text/plain]
Saving to: ‘car_fuel_efficiency_2026.csv.1’

car_fuel_efficiency 100%[===================>] 620.29K  --.-KB/s    in 0.009s

2026-09-17 10:50:24 (66.8 MB/s) - ‘car_fuel_efficiency_2026.csv.1’ saved [635180/635180]

In [9]:
df=pd.read_csv('car_fuel_efficiency_2026.csv')

# Q2 Number of records

In [10]:
print('No of records:',{df.shape[0]})

No of records: {10000}

# Q3. Fuel types: How many unique fuel types are present

In [11]:
df.columns

Index(['model_year', 'origin', 'fuel_type', 'drivetrain', 'num_doors',
       'engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'fuel_efficiency_mpg'],
      dtype='str')

In [12]:
len(df['fuel_type'].unique())

3

In [13]:
df["fuel_type"].nunique()

3

# Q4. Missing values: How many columns have missing value

In [14]:
df.describe()

,model_year,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
count,10000.000000,10000.00000,10000.000000,10000.000000,9123.000000,10000.000000,9736.000000,10000.000000
mean,1999.549500,3.50400,2268.807000,6.035200,254.446016,4286.754000,18.888044,29.997700
std,14.207925,0.95209,183.447355,0.542578,22.844613,266.212491,1.279543,2.930245
min,1975.000000,2.00000,1590.000000,4.000000,171.000000,3320.000000,14.000000,19.800000
25%,1987.000000,3.00000,2150.000000,6.000000,239.000000,4110.000000,18.000000,28.000000
50%,2000.000000,4.00000,2270.000000,6.000000,254.000000,4280.000000,18.900000,30.000000
75%,2012.000000,4.00000,2390.000000,6.000000,270.000000,4470.000000,19.700000,31.900000
max,2024.000000,5.00000,3110.000000,8.000000,334.000000,5460.000000,23.800000,41.200000

In [15]:
df.isnull().any().sum()

np.int64(2)

# Q5 Max fuel efficiency: Asian Vehicle

In [16]:
df.head(5)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [17]:
df.groupby('origin')['fuel_efficiency_mpg'].max()

origin
Asia      41.2
Europe    39.4
USA       38.2
Name: fuel_efficiency_mpg, dtype: float64

# Q6

# 6a Find the median value of the horsepower column in the dataset.

In [18]:
df['horsepower'].median()

np.float64(254.0)

# 6b. Next, calculate the most frequent value of the same horsepower column.

In [19]:
df['horsepower'].mode()

0    252.0
Name: horsepower, dtype: float64

# 6c Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.

In [20]:
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].mode()[0])

# 6 d Now, calculate the median value of horsepower once again.

In [21]:
df['horsepower'].median()

np.float64(252.0)

# Q7 a Sum of weights: Select all cars from Asia

In [72]:

asia_df = df[df['origin'] == 'Asia']
asia_df

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,252.0,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4
...,...,...,...,...,...,...,...,...,...,...,...
9984,2011,Asia,Gasoline,Front-wheel drive,3,2410,6,256.0,4610,20.2,32.4
9987,2004,Asia,Diesel,All-wheel drive,3,2180,6,266.0,4530,18.6,29.0
9990,1975,Asia,Diesel,Front-wheel drive,4,1940,6,236.0,3630,19.7,32.4
9994,1993,Asia,Gasoline,Rear-wheel drive,2,2360,6,257.0,4610,22.2,30.1
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0

# 7b Select only columns vehicle_weight and model_year

In [79]:

X = asia_df[['vehicle_weight', 'model_year']].values
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       ...,
       [3630, 1975],
       [4610, 1993],
       [4370, 1993]], shape=(2994, 2))

# 7C Select the first 7 values

In [ ]:
X=X[:7]
X
print(X.shape)  
print(X)

(7, 2)
[[4240 1996]
 [4310 1992]
 [4230 1997]
 [4420 1978]
 [3950 2007]
 [4750 2021]
 [4450 2019]]

# 7 D Get the underlying NumPy array. Let's call it X.

In [83]:
print(X.shape)  
print(X)

(7, 2)
[[4240 1996]
 [4310 1992]
 [4230 1997]
 [4420 1978]
 [3950 2007]
 [4750 2021]
 [4450 2019]]

In [84]:
X.shape

(7, 2)

# Q 7 E. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

In [85]:
XT = X.T
XT

array([[4240, 4310, 4230, 4420, 3950, 4750, 4450],
       [1996, 1992, 1997, 1978, 2007, 2021, 2019]])

In [86]:
XT.shape

(2, 7)

NameError: name 'T' is not defined

In [87]:
print(type(X))

<class 'numpy.ndarray'>

In [88]:
print(X.T)

[[4240 4310 4230 4420 3950 4750 4450]
 [1996 1992 1997 1978 2007 2021 2019]]

float64

In [89]:
                          # should show (7, 8)

XTX = X.T @ X
print(XTX.shape)                         # (8, 8)
print(XTX)

(2, 2)
[[131950500  60750580]
 [ 60750580  28041424]]

In [90]:
print(XTX)

[[131950500  60750580]
 [ 60750580  28041424]]

# Q7 F Invert XTX.

In [91]:
XTX_inv = np.linalg.inv(XTX)
print(XTX_inv)
print(XTX_inv.shape)

[[ 2.96830537e-06 -6.43071025e-06]
 [-6.43071025e-06  1.39675281e-05]]
(2, 2)

In [92]:
y= np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

print(y)
print(y.shape)

[1100 1300  800  900 1000 1100 1200]
(7,)

# Q7 G Multiply the inverse of XTX with the transpose of X, and then 
# multiply the result by y. Call the result w.

In [93]:
result=XTX_inv @ (X.T)

In [94]:
w=result @ y

# Q7 H What is the sum of result

In [95]:
final_sum=np.sum(w)
print(final_sum)

0.36919696904925486